#!/usr/bin/env python3
"""Reproduce the complete current Advanced snapshot from archived Konami HTML.

Network is deliberately excluded from generation. The fetched page digest and
the pinned CDB digest are recorded alongside the generated, factual card rows.
"""
from collections import Counter
from hashlib import sha256
from html.parser import HTMLParser
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / 'docs/audits/artifacts/tcg-complete-2026-10-08'


class TableParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.rows, self.row, self.cell = [], None, None

    def handle_starttag(self, tag, attrs):
        if tag == 'tr':
            self.row = []
        if tag in ('td', 'th') and self.row is not None:
            self.cell = []

    def handle_endtag(self, tag):
        if tag in ('td', 'th') and self.cell is not None:
            self.row.append(' '.join(''.join(self.cell).split()))
            self.cell = None
        if tag == 'tr' and self.row is not None:
            self.rows.append(self.row)
            self.row = None

    def handle_data(self, text):
        if self.cell is not None:
            self.cell.append(text)


def normalize(name):
    return ' '.join(name.casefold().split())


def main():
    archive = ARTIFACTS / 'official-advanced-list.html.txt'
    source = json.loads((ARTIFACTS / 'sources.json').read_text())['sources'][0]
    page = archive.read_bytes()
    assert sha256(page).hexdigest() == source['sha256']
    parser = TableParser()
    parser.feed(page.decode())
    rows = [r for r in parser.rows if len(r) == 5 and r[2] in
            ('Forbidden', 'Limited', 'Semi-Limited', 'Unlimited')]
    assert Counter(r[2] for r in rows) == {
        'Forbidden': 121, 'Limited': 94, 'Semi-Limited': 7, 'Unlimited': 9}
    assert len({normalize(r[1]) for r in rows}) == len(rows)

    database_path = ROOT / 'public/native/card-data.json'
    database_bytes = database_path.read_bytes()
    database = json.loads(database_bytes)
    by_name = {}
    cards = [dict(zip(database['columns'], r)) for r in database['rows']]
    aliases = {str(c['id']): str(c['alias']) for c in cards if c['alias']}
    for binding in database['canonicalBindings']:
        aliases[str(binding['sourceCode'])] = str(binding['canonicalCode'])
    for card in cards:
        by_name.setdefault(normalize(card['name']), []).append(card)
    entries = []
    for row in rows:
        matches = by_name.get(normalize(row[1]), [])
        assert matches, f'Unresolved official card name: {row[1]}'
        entries.append({'name': row[1], 'cardType': row[0], 'status': row[2],
                        'copyLimit': {'Forbidden': 0, 'Limited': 1,
                                      'Semi-Limited': 2, 'Unlimited': 3}[row[2]],
                        'codes': sorted({str(c['id']) for c in matches}, key=int),
                        'effectiveDate': '2026-09-28' if row[1] in
                        ('MIND MASTER', 'ELDER ENTITY NORDEN') else '2026-09-21'})
    metadata = {'id': 'TCG_EU_2026_09_21', 'asOf': '2026-10-08',
                'effectiveDate': '2026-09-21', 'sourceUrl': source['url'],
                'sourceSha256': source['sha256'], 'sourceBytes': len(page),
                'databaseSha256': sha256(database_bytes).hexdigest(),
                'databaseCommit': database['source']['commit'],
                'officialTableRows': len(entries),
                'restrictedNames': 222, 'forbidden': 121, 'limited': 94,
                'semiLimited': 7, 'newlyUnlimited': 9,
                'allOfficialNamesResolved': True,
                'delayedChanges': ['MIND MASTER', 'ELDER ENTITY NORDEN']}
    resolved = {'metadata': metadata, 'entries': entries,
                'trustedAliases': dict(sorted(aliases.items(), key=lambda x: int(x[0])))}
    (ARTIFACTS / 'resolved-advanced-list.json').write_text(
        json.dumps(resolved, ensure_ascii=False, indent=2) + '\n')
    stringify = lambda value: json.dumps(value, ensure_ascii=False, indent=2)
    (ROOT / 'src/core/tcg/TcgAdvancedBanlistData.js').write_text(
        '// Generated by scripts/generate-tcg-complete-format.py.\n'
        '// Complete factual Konami Advanced table; aliases from the pinned CDB.\n'
        'export const CURRENT_TCG_BANLIST_ID = "TCG_EU_2026_09_21";\n'
        f'export const TCG_ADVANCED_BANLIST_METADATA = Object.freeze({stringify(metadata)});\n'
        f'export const TCG_ADVANCED_BANLIST_ENTRIES = Object.freeze({stringify(entries)}\n'
        '  .map(entry => Object.freeze({ ...entry, codes: Object.freeze(entry.codes) })));\n'
        f'export const TCG_DECK_COPY_ALIASES = Object.freeze({stringify(resolved["trustedAliases"])});\n')
    print(json.dumps({'ok': True, 'rows': len(entries),
                      'restrictedNames': 222, 'trustedAliases': len(aliases)}))


if __name__ == '__main__':
    main()
