export const STARTER_CARDS = [
  {
    id: "89631139",
    name: "Dragon Blanc aux Yeux Bleus",
    name_en: "Blue-Eyes White Dragon",
    type: "Normal Monster",
    desc: "Ce dragon légendaire est une bête puissante détruisant tout sur son passage. Très peu de duellistes ont vu cette carte et ont survécu pour en témoigner.",
    atk: 3000,
    def: 2500,
    level: 8,
    race: "Dragon",
    attribute: "LIGHT",
    card_type: "monster"
  },
  {
    id: "46986414",
    name: "Magicien Sombre",
    name_en: "Dark Magician",
    type: "Normal Monster",
    desc: "Le plus grand magicien en termes d'attaque et de défense.",
    atk: 2500,
    def: 2100,
    level: 7,
    race: "Spellcaster",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "74677422",
    name: "Dragon Noir aux Yeux Rouges",
    name_en: "Red-Eyes Black Dragon",
    type: "Normal Monster",
    desc: "Un dragon féroce dont l'attaque est mortelle.",
    atk: 2400,
    def: 2000,
    level: 7,
    race: "Dragon",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "38033121",
    name: "Magicienne Sombre",
    name_en: "Dark Magician Girl",
    type: "Effect Monster",
    desc: "Gagne 300 ATK pour chaque 'Magicien Sombre' ou 'Magicien Sombre du Chaos' dans les Cimetières.",
    atk: 2000,
    def: 1700,
    level: 6,
    race: "Spellcaster",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "70781052",
    name: "Crâne Invoqué",
    name_en: "Summoned Skull",
    type: "Normal Monster",
    desc: "Démon doté de pouvoirs intellectuels et d'une force d'attaque impressionnante.",
    atk: 2500,
    def: 1200,
    level: 6,
    race: "Fiend",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "91152256",
    name: "Gardien Celtique",
    name_en: "Celtic Guardian",
    type: "Normal Monster",
    desc: "Un elfe qui a appris à manier l'épée, il trompe ses ennemis en attaquant avec agilité.",
    atk: 1400,
    def: 1200,
    level: 4,
    race: "Warrior",
    attribute: "EARTH",
    card_type: "monster"
  },
  {
    id: "40640057",
    name: "Kuriboh",
    name_en: "Kuriboh",
    type: "Effect Monster",
    desc: "Durant le calcul des dommages, vous pouvez défausser cette carte pour réduire les dommages de combat de ce combat à 0.",
    atk: 300,
    def: 200,
    level: 1,
    race: "Fiend",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "13039848",
    name: "Soldat de Pierre Géant",
    name_en: "Giant Soldier of Stone",
    type: "Normal Monster",
    desc: "Un guerrier de pierre géant. Sa défense est extrêmement solide.",
    atk: 1300,
    def: 2000,
    level: 3,
    race: "Rock",
    attribute: "EARTH",
    card_type: "monster"
  },
  {
    id: "88819587",
    name: "Bébé Dragon",
    name_en: "Baby Dragon",
    type: "Normal Monster",
    desc: "Plus qu'un bébé dragon, cette créature possède un grand potentiel encore inexploité.",
    atk: 1200,
    def: 700,
    level: 3,
    race: "Dragon",
    attribute: "WIND",
    card_type: "monster"
  },
  {
    id: "71625222",
    name: "Magicien du Temps",
    name_en: "Time Wizard",
    type: "Effect Monster",
    desc: "Une fois par tour : vous pouvez lancer une pièce. Si vous gagnez, détruisez tous les monstres contrôlés par votre adversaire. Si vous perdez, détruisez tous vos propres monstres.",
    atk: 500,
    def: 400,
    level: 2,
    race: "Spellcaster",
    attribute: "LIGHT",
    card_type: "monster"
  },
  {
    id: "63977008",
    name: "Robot Synchronique",
    name_en: "Junk Synchron",
    type: "Tuner Monster",
    desc: "Lorsqu'il est Invoqué Normalement, il peut ramener un monstre de Niveau 2 ou moins du Cimetière en Défense avec ses effets annulés.",
    atk: 1300,
    def: 500,
    level: 3,
    race: "Warrior",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "83764718",
    name: "Monster Reborn",
    name_en: "Monster Reborn",
    type: "Spell Card",
    desc: "Ciblez 1 monstre dans l'un des Cimetières ; Invoquez-le Spécialement sur votre Terrain.",
    atk: 0,
    def: 0,
    level: 0,
    race: "Normal",
    attribute: "SPELL",
    card_type: "spell"
  },
  {
    id: "12580477",
    name: "Raigeki",
    name_en: "Raigeki",
    type: "Spell Card",
    desc: "Détruisez tous les monstres contrôlés par votre adversaire.",
    atk: 0,
    def: 0,
    level: 0,
    race: "Normal",
    attribute: "SPELL",
    card_type: "spell"
  },
  {
    id: "55144522",
    name: "Pot de Cupidité",
    name_en: "Pot of Greed",
    type: "Spell Card",
    desc: "Piochez 2 cartes de votre Deck.",
    atk: 0,
    def: 0,
    level: 0,
    race: "Normal",
    attribute: "SPELL",
    card_type: "spell"
  },
  {
    id: "44095762",
    name: "Force de Miroir",
    name_en: "Mirror Force",
    type: "Trap Card",
    desc: "Lorsqu'un monstre de l'adversaire déclare une attaque : détruisez tous les monstres en Position d'Attaque contrôlés par votre adversaire.",
    atk: 0,
    def: 0,
    level: 0,
    race: "Normal",
    attribute: "TRAP",
    card_type: "trap"
  },
  {
    id: "04206964",
    name: "Trappe",
    name_en: "Trap Hole",
    type: "Trap Card",
    desc: "Quand votre adversaire Invoque Normalement ou Invoque par Flip un monstre avec 1000 ATK ou plus : ciblez ce monstre ; détruisez la cible.",
    atk: 0,
    def: 0,
    level: 0,
    race: "Normal",
    attribute: "TRAP",
    card_type: "trap"
  },
  {
    id: "24094653",
    name: "Polymérisation",
    name_en: "Polymerization",
    type: "Spell Card",
    desc: "Invoquez par Fusion 1 Monstre Fusion depuis votre Extra Deck, en utilisant des monstres depuis votre main ou Terrain comme Matériel Fusion.",
    atk: 0,
    def: 0,
    level: 0,
    race: "Normal",
    attribute: "SPELL",
    card_type: "spell"
  },
  {
    id: "05053103",
    name: "Bœuf de Combat",
    name_en: "Battle Ox",
    type: "Normal Monster",
    desc: "Un monstre à la puissance foudroyante qui détruit ses ennemis d'un simple coup de hache.",
    atk: 1700,
    def: 1000,
    level: 4,
    race: "Beast-Warrior",
    attribute: "EARTH",
    card_type: "monster"
  },
  {
    id: "97590747",
    name: "La Jinn, Génie Mystique de la Lampe",
    name_en: "La Jinn the Mystical Genie of the Lamp",
    type: "Normal Monster",
    desc: "Un génie de la lampe au service de son maître.",
    atk: 1800,
    def: 1000,
    level: 4,
    race: "Fiend",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "14898066",
    name: "Vorse Raider",
    name_en: "Vorse Raider",
    type: "Normal Monster",
    desc: "Cette bête guerrière manipule une grande variété d'armes.",
    atk: 1900,
    def: 1200,
    level: 4,
    race: "Beast-Warrior",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "66602787",
    name: "Saggi le Bouffon des Ténèbres",
    name_en: "Saggi the Dark Clown",
    type: "Normal Monster",
    desc: "Un bouffon des ténèbres qui utilise des attaques étranges.",
    atk: 600,
    def: 1500,
    level: 3,
    race: "Spellcaster",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "15025844",
    name: "Elfe Mystique",
    name_en: "Mystical Elf",
    type: "Normal Monster",
    desc: "Une elfe délicate possédant une défense renforcée par un pouvoir mystique.",
    atk: 800,
    def: 2000,
    level: 4,
    race: "Spellcaster",
    attribute: "LIGHT",
    card_type: "monster"
  },
  {
    id: "41392891",
    name: "Démon Sauvage",
    name_en: "Feral Imp",
    type: "Normal Monster",
    desc: "Un petit démon agile qui attaque avec ses griffes.",
    atk: 1300,
    def: 1400,
    level: 4,
    race: "Fiend",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "32452818",
    name: "Guerrier Castor",
    name_en: "Beaver Warrior",
    type: "Normal Monster",
    desc: "Cette créature se retranche en défense lorsqu'elle combat dans la prairie.",
    atk: 1200,
    def: 1500,
    level: 4,
    race: "Beast-Warrior",
    attribute: "EARTH",
    card_type: "monster"
  },
  {
    id: "28279543",
    name: "Malédiction du Dragon",
    name_en: "Curse of Dragon",
    type: "Normal Monster",
    desc: "Un dragon malfaisant qui exploite les forces des ténèbres.",
    atk: 2000,
    def: 1500,
    level: 5,
    race: "Dragon",
    attribute: "DARK",
    card_type: "monster"
  },
  {
    id: "06368038",
    name: "Gaïa le Chevalier Implacable",
    name_en: "Gaia The Fierce Knight",
    type: "Normal Monster",
    desc: "Un chevalier dont le cheval voyage plus vite que le vent.",
    atk: 2300,
    def: 2100,
    level: 7,
    race: "Warrior",
    attribute: "EARTH",
    card_type: "monster"
  },
  {
    id: "48305365",
    name: "Assaillant à la Hache",
    name_en: "Axe Raider",
    type: "Normal Monster",
    desc: "Un guerrier maniant une hache avec une force extraordinaire.",
    atk: 1700,
    def: 1150,
    level: 4,
    race: "Warrior",
    attribute: "EARTH",
    card_type: "monster"
  },
  {
    id: "64428736",
    name: "Épée de l'Alligator",
    name_en: "Alligator's Sword",
    type: "Normal Monster",
    desc: "Un alligator guerrier expert dans le maniement de l'épée.",
    atk: 1500,
    def: 1200,
    level: 4,
    race: "Beast",
    attribute: "EARTH",
    card_type: "monster"
  },
  {
    id: "44287299",
    name: "Masaki le Spadassin Légendaire",
    name_en: "Masaki the Legendary Swordsman",
    type: "Normal Monster",
    desc: "Un épéiste de légende reconnu pour ses attaques rapides.",
    atk: 1100,
    def: 1100,
    level: 4,
    race: "Warrior",
    attribute: "EARTH",
    card_type: "monster"
  },
  {
    id: "49791927",
    name: "Hache du Tigre",
    name_en: "Tiger Axe",
    type: "Normal Monster",
    desc: "Un guerrier tigre armé d'une hache redoutable.",
    atk: 1300,
    def: 1100,
    level: 4,
    race: "Beast-Warrior",
    attribute: "EARTH",
    card_type: "monster"
  }
];

export function normalizeCardImageId(id) {
  const value = String(id ?? '');
  return /^\d+$/.test(value) ? value.replace(/^0+(?=\d)/, '') : value;
}

export function getCardImageUrl(id) {
  return `https://images.ygoprodeck.com/images/cards/${normalizeCardImageId(id)}.jpg`;
}

export function getCardCroppedImageUrl(id) {
  return `https://images.ygoprodeck.com/images/cards_cropped/${normalizeCardImageId(id)}.jpg`;
}

export const EXTRA_DECK_CARDS = [
  {
    id: "23995346",
    name: "Dragon Ultime aux Yeux Bleus",
    name_en: "Blue-Eyes Ultimate Dragon",
    type: "Fusion Monster",
    desc: "\"Dragon Blanc aux Yeux Bleus\" + \"Dragon Blanc aux Yeux Bleus\" + \"Dragon Blanc aux Yeux Bleus\". (ATK 4500 / DEF 3800)",
    atk: 4500,
    def: 3800,
    level: 12,
    race: "Dragon",
    attribute: "LIGHT",
    card_type: "monster",
    extra_type: "fusion",
    belongsInExtraDeck: true,
    fusionMaterials: ["89631139", "89631139", "89631139"]
  },
  {
    id: "44508094",
    name: "Dragon Poussière d'Étoile",
    name_en: "Stardust Dragon",
    type: "Synchro Monster",
    rulesText: "1 Syntoniseur + 1 monstre non-Syntoniseur ou plus. Lorsqu'une carte ou un effet qui va détruire une ou plusieurs cartes sur le Terrain est activé (Effet Rapide) : vous pouvez Sacrifier cette carte ; annulez l'activation, et si vous le faites, détruisez-la. Durant la End Phase, Invoquez Spécialement cette carte si elle a activé cet effet ce tour.",
    desc: "1 Syntoniseur + 1 monstre non-Syntoniseur ou plus. (ATK 2500 / DEF 2000)",
    atk: 2500,
    def: 2000,
    level: 8,
    race: "Dragon",
    attribute: "WIND",
    card_type: "monster",
    extra_type: "synchro",
    belongsInExtraDeck: true,
    effectCode: "STARDUST_NEGATE_DESTRUCTION"
  },
  {
    id: "31924889",
    name: "Magicien des Arcanes",
    name_en: "Arcanite Magician",
    type: "Synchro Monster",
    rulesText: "1 Syntoniseur + 1 monstre non-Syntoniseur Magicien ou plus. Lors de son Invocation Synchro, placez 2 Compteurs Magie sur cette carte. Elle gagne 1000 ATK pour chaque Compteur Magie. Vous pouvez retirer 1 Compteur Magie, puis ciblez 1 carte contrôlée par votre adversaire ; détruisez la cible.",
    desc: "1 Syntoniseur + 1 monstre non-Syntoniseur Magicien ou plus. Lors de son Invocation Synchro, il reçoit 2 Compteurs Magie et gagne 1000 ATK par compteur.",
    atk: 400,
    def: 1800,
    level: 7,
    race: "Spellcaster",
    attribute: "LIGHT",
    card_type: "monster",
    extra_type: "synchro",
    belongsInExtraDeck: true,
    effectCode: "ARCANITE_COUNTERS",
    synchroNonTunerRace: "Spellcaster"
  }
];
